name = "PlotExTinyMD"
uuid = "fe7bca5e-e784-4ba9-bf53-4509fbafe88d"
authors = ["Xuanzhao Gao <gaoxuanzhao@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ExTinyMD = "fec76197-d59f-46dd-a0ed-76a83c21f7aa"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
julia = "1"
ExTinyMD = "0.2"
GLMakie = "0.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
